alias cd='z'
alias ls='eza --icons -H --group-directories-first --git -g'
alias tree='eza --icons -F -H --tree -r'
alias utopi='utop -init src/assignment.ml'
alias gcp='function _gcp() { git commit -am "$1" && git push; }; _gcp'
alias gcz='function _gcz() { git clone "$1" && cd "$(basename "$1" .git)" && nvim .; }; _gcz'
alias la='ls -a'
alias ll='ls -l'
alias ex='exit'
alias nv='nvim .'
alias pys='python ~/PyShell.py'
alias et='emacsclient -nw -cq'
alias em='emacsclient -cqn'
alias ets='f() { emacsclient -nw -cq "/sudo::${1}"; }; f'
alias es='SUDO_EDITOR="emacsclient -t" sudoedit'
alias bc='bc -ql ~/.bcrc'
alias gtree='git log --graph --decorate --all --color=always \
--pretty=format:"%C(auto)%h %C(bold blue)%d %C(reset)%C(green)%an%C(reset) %s"'
alias qrcode='f() { qrencode -t ANSIUTF8 "${1}"; }; f'
alias ssh='kitten ssh'